version: '3.6'

services:
  db:
    image: postgres:alpine
#    restart: always
    ports:
      - "${PG_PORT}:5432"
    environment:
      - PG_ROOT_PASSWORD
      - PG_DATABASE
      - PG_USER
      - PG_PASSWORD
      - TZ=${PG_TZ}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - ${PG_PORT}
  adminer:
    image: adminer
    ports:
      - 8080:8080
